### ISSUE TITLE
Crash on launch

### ISSUE THREAD

**Issue by katubug** [SammySemicolon/MinersDelight#12]
Hi! I went to add this mod to my Cottage Witch modpack, but it prevents the game from starting. Seems like it might be an incompatibility with SuperMartijn642 Core Library?

[crash-2023-04-25_10.49.50-client.txt](https://github.com/SammySemicolon/MinersDelight/files/11327019/crash-2023-04-25_10.49.50-client.txt)

**Comment by SammySemicolon** [comment]
Hey so, this is actually an issue with central kitchen and the core library.
It's a mixin conflict from a mixin from central kitchen that tries to modify the brewing and chewing keg. Nothing to do with Miner's Delight here.

**Comment by katubug** [comment]
Ah, thank you! I totally misunderstood as I thought the only change I'd
made was to add your mod. My mistake! Thanks very much for the correction.

**Comment by SammySemicolon** [comment]
No worries :)
