### ISSUE TITLE
Add a config option to disable squids from dropping raw squid and raw squid tentacles

### ISSUE THREAD

**Issue by DarthCaesium** [SammySemicolon/MinersDelight#15]
I use Cultural Delights, which is a mod that also adds raw squid, cooked squid, raw glow squid, raw squid tentacles and cooked squid tentacles. I much prefer their system, but want to have this mod for its other features. Could you provide a way in the config files to completely disable the drops that you add to the squid? Also, for the sake of people who might encounter this with other mobs, say bats for example, could you provide the same for other mob drops that this mod adds?

**Comment by SammySemicolon** [comment]
You can remove the functionality from miner's delight using datapacks, I know that for a fact but honestly can't explain how. Look into Global Loot Modiifers.
