### ISSUE TITLE
[1.19.2 Forge] add recipes in JEI please.

### ISSUE THREAD

**Issue by MrJorman** [SammySemicolon/MinersDelight#17]
add please all recipes in JEI in Copper pot.
![image](https://github.com/SammySemicolon/MinersDelight/assets/55187962/111c881d-0080-4328-bb32-f509a52e4429)

**Comment by SammySemicolon** [comment]
What? the recipe you input isn't even right, the copper pot isn't being heated, and recipes DO show up in JEI.

**Comment by MrJorman** [comment]
no showing.

**Comment by MrJorman** [comment]
NO worning in SERVER! i testing!!!
