### ISSUE TITLE
incompatibility with cultural delight

### ISSUE THREAD

**Issue by Aceplante2** [SammySemicolon/MinersDelight#18]
Specifically squids. Both of your mods add a squid item that can then be cut. Perhaps you can detect if cultural delights is installed and just add the tentacles to that recipe? It seems weird getting 2 squid items from each squid

forge 1.18.2

**Comment by SammySemicolon** [comment]
You can turn off squid drops from miner's delight using datapacks. This is the norm nowadays, rather than having config options, people can edit any kind of loot table using datapacks.
