### ISSUE TITLE
Incompatibility with Immersive Weathering: Cave Carrots cannot be grown as crops on Mulch (1.18.2)

### ISSUE THREAD

**Issue by KillJestah** [SammySemicolon/MinersDelight#19]
If Cave Carrots are placed as crops on Immersive Weathering's Mulch, the game crashes because it seems to forget the Cave Carrot growth stages. I assume it's because Mulch is not tilled like Vanilla farmland or Farmer's Delight's Rich Soil, therefore the crop gets confused on what to do. It can be planted, but attempting to grow crashes the game.

[Miner's Delight + 1.18.2-1.1.1]
[Immersive Weathering 1.18.2-3.0.3]

**Comment by SammySemicolon** [comment]
The same thing happened with farmer's delight tomatoes, and a whole bunch of other crops. This isn't something Miner's Delight can fix I wanna say.

**Comment by KillJestah** [comment]
Thanks for looking into this regardless! Yeah, I think Immersive Weathering messes with crops, even when it shouldn't be possible.
