### ISSUE TITLE
Copper Pot doesn't preserve cooked (but not served) meals

### ISSUE THREAD

**Issue by Lgmrszd** [SammySemicolon/MinersDelight#22]
This is one of cool features of Farmer's Delight Cooking Pot, it allows carrying around a pot with up to 64 stack of cooked meals that usually only stack to 16.
When breaking Copper Pot with cooked meals inside and then placing it again, meals are gone.
This happens on 1.18.2, version 1.1.2

**Comment by SammySemicolon** [comment]
![image](https://github.com/SammySemicolon/MinersDelight/assets/69329424/61c626a8-3513-41fb-9f93-7c10c0878796)
Fixed it up, long overdue but alas.
